//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public long ID { get; set; }
        public string UsernameO { get; set; }
        public string UsernameU { get; set; }
        public string Email { get; set; }
        public Nullable<long> IDJob { get; set; }
        public string ImgCV { get; set; }
        public string Status { get; set; }
    
        public virtual AccountOrganization AccountOrganization { get; set; }
        public virtual AccountPerson AccountPerson { get; set; }
        public virtual Job Job { get; set; }
    }
}
