//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long IDBlog { get; set; }
        public long IDComment { get; set; }
        public string Username { get; set; }
        public string Comment1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
