//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkITEntities : DbContext
    {
        public WorkITEntities()
            : base("name=WorkITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountAdministrator> AccountAdministrators { get; set; }
        public virtual DbSet<AccountOrganization> AccountOrganizations { get; set; }
        public virtual DbSet<AccountPerson> AccountPersons { get; set; }
        public virtual DbSet<Apply> Applies { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
    }
}
